// ai-attribution opencode port Integration Test - Design Doc: docs/design/opencode-port-design.md, "Slice:
// ai-attribution". Contract: ADR-0002 (decision table, family table). ACs: AC-033, AC-034.
//
// Run with (HOME and the bun caches pointed outside the real home):
//
//   bun test plugin-attribution/tests
//
// Harness (scripts/opencode/tests/support/scope.ts):
// - Each test builds a temp scope under os.tmpdir(): HOME=<tmp>/home, XDG_CONFIG_HOME=<tmp>/config, and
//   <tmp>/config/opencode/plugins as a symlink to <tmp>/dotfiles/plugins (the live layout). The port is copied there
//   and dynamic-imported with a unique query string, so every test gets a fresh module and fresh per-session state.
// - The factory gets a fake client (client.app.log records calls). The tests drive the port's hooks directly:
//   config (MCP server names), chat.params (model family), event (session.deleted) and tool.execute.before.
// - In-process tests always write the reviewer name to the primary file under the scope's XDG_CONFIG_HOME, so the
//   port never reaches the legacy fallbacks. Those hang off os.homedir(), which Bun caches at startup: HOME set here
//   cannot move them.
// - The name-file tests that need the legacy fallbacks, or no name at all, run the port in a child bun whose HOME is
//   the scope's, so its cached os.homedir() is too. Only PATH is inherited by the child.
// - The slop, commit-trailer and validator cases are the ones plugin-attribution/tests/test_attribution_hook.py
//   asserts against the Python hook, so both runtimes keep the same pattern lists.

import { afterEach, describe, expect, test } from "bun:test"
import { spawnSync } from "node:child_process"
import { chmodSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import {
  copyPort, type EnvVars, fakeClient, importPort, makeScope, type Scope, scopeEnv, withEnv,
} from "../../scripts/opencode/tests/support/scope"

const PORT = "plugin-attribution/plugins/opencode-ai-attribution.ts"
const EXPORT = "AiAttributionPlugin"

const NAME = "Jane Reviewer"
const OTHER_NAME = "Someone Else"
const ROBOT = "\u{1F916}"
const SESSION = "ses_test"
const OTHER_SESSION = "ses_other"
const IS_ROOT = process.getuid?.() === 0

const MCP_TOOL = "mcp__github__create_issue"
const GITHUB_TOOL = "github-mcp_create_issue"
const SLACK_TOOL = "slack_post_message"
// The MCP servers a user's opencode.json might hold; the port only reads the keys.
const MCP_SERVERS = {
  "github-mcp": { type: "remote", url: "https://example.invalid/mcp" },
  slack: { type: "local", command: ["slack-mcp"] },
}

const GPT_5 = { id: "gpt-5", providerID: "openai" }
const CLAUDE_SONNET = { id: "claude-sonnet-4", providerID: "anthropic" }

const SETUP_MESSAGE = [
  "[ai-attribution] BLOCKED: Reviewer name not configured.",
  "",
  "Before posting to external platforms, set up your attribution name.",
  "Ask the user for their name and save it:",
  "",
  '  mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/llm-agent-workflow"',
  '  echo "Their Name" > "${XDG_CONFIG_HOME:-$HOME/.config}/llm-agent-workflow/attribution-name.txt"',
  "",
  "Then show the complete post content to the user for approval before retrying.",
].join("\n")

const COMMIT_TRAILER_MESSAGE = [
  "[ai-attribution] BLOCKED: AI-generated trailer detected in commit message.",
  "",
  "Remove AI attribution trailers from the commit message:",
  '  - "Co-authored-by:" lines naming an AI model or assistant',
  '  - "generated by/with <AI>" or "assisted by <AI>" lines',
  "",
  "Keep the commit message concise, factual, and free of AI attribution. Then",
  "retry the commit.",
].join("\n")

type Hook = (input: unknown, output?: unknown) => Promise<void>

interface Attribution {
  config(mcp?: Record<string, unknown>): Promise<void>
  params(sessionID: string, model: object): Promise<void>
  deleted(sessionID: string): Promise<void>
  tool(sessionID: string, tool: string, args: Record<string, unknown>): Promise<void>
  bash(sessionID: string, command: string): Promise<void>
  logs: unknown[]
}

interface ChildResult {
  allowed: boolean
  message: string
}

const scopes: Scope[] = []

afterEach(() => {
  for (const scope of scopes.splice(0)) scope.cleanup()
})

function newScope(): Scope {
  const scope = makeScope({ kind: "global", symlinkPlugins: true })
  scopes.push(scope)
  return scope
}

// The attribution line for FAMILY and NAME, as the block message suggests it.
function line(family: string, name = NAME): string {
  return `${ROBOT} Written by ${family}, reviewed by ${name}`
}

function missingMessage(family: string, name = NAME): string {
  return [
    "[ai-attribution] BLOCKED: Attribution line missing from post body.",
    "",
    "All external posts must include this attribution line:",
    "",
    `  ${line(family, name)}`,
    "",
    "IMPORTANT: Before retrying, you MUST:",
    "1. Add the attribution line to the post body",
    "2. Show the COMPLETE post content to the user",
    "3. Ask the user to approve before posting",
    "4. Only retry after user confirms",
  ].join("\n")
}

function slopMessage(phrases: string): string {
  return [
    "[ai-attribution] BLOCKED: AI-slop filler detected in post content.",
    "",
    "Remove these phrases and rewrite with concrete, specific language:",
    `  ${phrases}`,
    "",
    "Prefer plain, factual wording that states what changed and why. For review",
    "comments, structure feedback as: location -> problem -> proposed fix.",
    "",
    "IMPORTANT: Rewrite the content, show the COMPLETE updated post to the user,",
    "and get approval before retrying.",
  ].join("\n")
}

function mcpAllowedLog(tool: string): unknown {
  return { body: { service: "ai-attribution", level: "info", message: `MCP post allowed with attribution (${tool})` } }
}

const BASH_ALLOWED_LOG = {
  body: { service: "ai-attribution", level: "info", message: "Bash posting command allowed with attribution" },
}

function post(body: string): Record<string, unknown> {
  return { title: "Fix flaky test", body }
}

function primaryNameFile(configHome: string): string {
  return join(configHome, "llm-agent-workflow", "attribution-name.txt")
}

function legacyOpencodeNameFile(home: string): string {
  return join(home, ".config", "opencode", "claude-attribution-name.txt")
}

function legacyClaudeCodeNameFile(home: string): string {
  return join(home, ".claude", "claude-attribution-name.txt")
}

function writeName(path: string, content: string | Uint8Array): string {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  return path
}

async function startPlugin(scope: Scope): Promise<Attribution> {
  const module = await importPort(copyPort(scope, PORT))
  const factory = module[EXPORT] as (input: Record<string, unknown>) => Promise<Record<string, Hook>>
  const { client, logs } = fakeClient()
  const hooks = await factory({ client, directory: scope.projectDir, worktree: scope.projectDir })
  const tool = (sessionID: string, name: string, args: Record<string, unknown>) =>
    hooks["tool.execute.before"]({ tool: name, sessionID, callID: "call_test" }, { args })
  return {
    config: (mcp) => hooks.config(mcp === undefined ? {} : { mcp }),
    params: (sessionID, model) =>
      hooks["chat.params"](
        { sessionID, agent: "build", model, provider: { source: "config", info: {}, options: {} }, message: {} },
        { temperature: 0, topP: 1, topK: 0, maxOutputTokens: undefined, options: {} },
      ),
    deleted: (sessionID) =>
      hooks.event({ event: { type: "session.deleted", properties: { info: { id: sessionID } } } }),
    tool,
    bash: (sessionID, command) => tool(sessionID, "bash", { command }),
    logs,
  }
}

// Runs FN against a freshly imported port, with the reviewer name in the scope's primary file and the scope's env.
async function withPlugin(fn: (plugin: Attribution, scope: Scope) => Promise<void>): Promise<void> {
  const scope = newScope()
  writeName(primaryNameFile(scope.configHome), NAME)
  await withEnv(scopeEnv(scope), async () => fn(await startPlugin(scope), scope))
}

async function blocked(call: Promise<unknown>): Promise<string> {
  try {
    await call
  } catch (error) {
    if (error instanceof Error) return error.message
    throw new Error(`the call rejected with a non-Error: ${String(error)}`)
  }
  throw new Error("expected the call to throw, but it returned")
}

describe("opencode-ai-attribution: the model-aware line (AC-033)", () => {
  // AC-033: "after chat.params with { id: "gpt-5", providerID: "openai" }, a missing line throws a message whose
  //   suggestion is the GPT line; a GPT line and a Claude line both pass; chat.params with { id: "claude-sonnet-4",
  //   providerID: "anthropic" } does not throw; an unknown model suggests AI; after session.deleted the family falls
  //   back to AI."
  test("after chat.params for gpt-5 on openai, a post without the line is blocked with the GPT line", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("GPT"))
    })
  })

  test("in a GPT session, a GPT line and a Claude line both pass", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      await plugin.tool(SESSION, MCP_TOOL, post(`Fixes the timeout.\n\n${line("GPT")}`))
      await plugin.tool(SESSION, MCP_TOOL, post(`Fixes the timeout.\n\n${line("Claude")}`))

      expect(plugin.logs).toEqual([mcpAllowedLog(MCP_TOOL), mcpAllowedLog(MCP_TOOL)])
    })
  })

  test("chat.params for claude-sonnet-4 on anthropic does not throw, and the Claude line is suggested", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, CLAUDE_SONNET)

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("Claude"))
    })
  })

  test("an unknown model suggests the AI line", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, { id: "phi-4", providerID: "local-lab" })

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("a session chat.params never saw is still checked, and suggests the AI line", async () => {
    await withPlugin(async (plugin) => {
      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("after session.deleted the family falls back to AI", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)
      await plugin.deleted(SESSION)

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("the family is per session, and session.deleted clears only its own session", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)
      await plugin.params(OTHER_SESSION, CLAUDE_SONNET)
      await plugin.deleted(OTHER_SESSION)

      const kept = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))
      const cleared = await blocked(plugin.tool(OTHER_SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect([kept, cleared]).toEqual([missingMessage("GPT"), missingMessage("AI")])
    })
  })

  test("the latest chat.params for a session sets its family", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)
      await plugin.params(SESSION, CLAUDE_SONNET)

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("Claude"))
    })
  })

  test("chat.params never reads modelID", async () => {
    await withPlugin(async (plugin) => {
      const model = { id: "gpt-5", providerID: "anthropic" }
      Object.defineProperty(model, "modelID", {
        get() {
          throw new Error("modelID was read")
        },
      })

      await plugin.params(SESSION, model)
      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("GPT"))
    })
  })

  test("chat.params with a model that has no id or providerID suggests AI and does not throw", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, {})

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  // ADR-0002 family table: case-insensitive substrings of the model id first, then the providerID; no match is AI.
  // "in-house-model" holds no id term, so those rows resolve through the providerID alone.
  test.each([
    ["claude-opus-4-1", "github-copilot", "Claude"],
    ["anthropic/claude-sonnet-4", "openrouter", "Claude"],
    ["Claude-Sonnet-4", "amazon-bedrock", "Claude"],
    ["in-house-model", "anthropic", "Claude"],
    ["gpt-4.1", "github-copilot", "GPT"],
    ["o1", "azure", "GPT"],
    ["o3-mini", "azure", "GPT"],
    ["o4-mini", "azure", "GPT"],
    ["codex-mini-latest", "azure", "GPT"],
    ["in-house-model", "openai", "GPT"],
    ["in-house-model", "OpenAI", "GPT"],
    ["gemini-2.5-pro", "openrouter", "Gemini"],
    ["gemma-3-27b", "ollama", "Gemini"],
    ["in-house-model", "google", "Gemini"],
    ["in-house-model", "google-vertex", "Gemini"],
    ["deepseek/deepseek-chat-v3.1", "openrouter", "DeepSeek"],
    ["mistral-large-latest", "openrouter", "Mistral"],
    ["codestral-latest", "openrouter", "Mistral"],
    ["devstral-medium", "openrouter", "Mistral"],
    ["llama-3.3-70b-versatile", "groq", "Llama"],
    ["qwen3-coder", "openrouter", "Qwen"],
    ["grok-4", "openrouter", "Grok"],
    ["in-house-model", "xai", "Grok"],
    ["kimi-k2", "openrouter", "Kimi"],
    ["in-house-model", "moonshotai", "Kimi"],
    ["glm-4.6", "openrouter", "GLM"],
    ["in-house-model", "zhipuai", "GLM"],
    ["in-house-model", "zai", "GLM"],
    ["in-house-model", "zai-coding-plan", "GLM"],
    ["phi-4", "ollama", "AI"],
    ["in-house-model", "local-lab", "AI"],
  ])("model %s on provider %s suggests the %s line", async (id, providerID, family) => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, { id, providerID })

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage(family))
    })
  })
})

describe("opencode-ai-attribution: the validator accepts any family on one line", () => {
  test.each([
    ["the Claude line", `Fixed the flaky test.\n\n${line("Claude")}`],
    ["a line without the emoji", "Fixed the flaky test.\n\nWritten by Claude, reviewed by Jane Reviewer"],
    ["another family", `Fixed the flaky test.\n\n${line("GPT")}`],
    ["a multi-word family", "Written by Claude Opus 4, reviewed by Jane Reviewer"],
    ["the pre-2.0 line without a comma", "Written by Claude reviewed by Jane Reviewer"],
    ["a 40-character family", `Written by ${"F".repeat(40)}, reviewed by Jane Reviewer`],
    ["any letter case", "WRITTEN BY gpt, REVIEWED BY jane reviewer"],
  ])("a post with %s passes", async (_label, body) => {
    await withPlugin(async (plugin) => {
      await plugin.tool(SESSION, MCP_TOOL, post(body))

      expect(plugin.logs).toEqual([mcpAllowedLog(MCP_TOOL)])
    })
  })

  test.each([
    ["no line", "Fixed the flaky test."],
    ["another reviewer", `Fixed the flaky test.\n\n${line("Claude", OTHER_NAME)}`],
    ["an empty family", "Written by , reviewed by Jane Reviewer"],
    ["a whitespace-only family", "Written by    , reviewed by Jane Reviewer"],
    ["a 41-character family", `Written by ${"F".repeat(41)}, reviewed by Jane Reviewer`],
    ["a family with a comma", "Written by Claude, Inc, reviewed by Jane Reviewer"],
    ["a line split before reviewed by", `${ROBOT} Written by GPT,\nreviewed by Jane Reviewer`],
    ["a line split after written by", `${ROBOT} Written by\nClaude, reviewed by Jane Reviewer`],
    ["a family split across lines", `${ROBOT} Written by Claude\nOpus 4, reviewed by Jane Reviewer`],
  ])("a post with %s is blocked", async (_label, body) => {
    await withPlugin(async (plugin) => {
      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post(body)))

      expect(message).toBe(missingMessage("AI"))
    })
  })
})

describe("opencode-ai-attribution: every check runs for a GPT session", () => {
  // Negative from Task 3.1: the commit-trailer and slop checks run for a GPT session (1.x skipped every check for a
  // model it did not see as Claude).
  test.each([
    [
      "a Co-authored-by trailer",
      'git commit -m "fix: retry backoff\n\nCo-authored-by: Claude 3.7 Sonnet <noreply@anthropic.com>"',
    ],
    ["a generated-by footer", 'git commit -m "feat: parser\n\nGenerated by Claude"'],
    ["an assisted-by footer", 'git commit -m "refactor: moved types\n\nAssisted by Copilot"'],
    ["combined short flags", 'git commit -am "fix: backoff\n\nCo-authored-by: Claude <noreply@anthropic.com>"'],
    ["a second -m", 'git commit -m "fix: backoff" -m "Generated with ChatGPT"'],
  ])("a git commit with %s is blocked", async (_label, command) => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      const message = await blocked(plugin.bash(SESSION, command))

      expect(message).toBe(COMMIT_TRAILER_MESSAGE)
    })
  })

  test("a git commit -F whose file carries an AI trailer is blocked", async () => {
    await withPlugin(async (plugin, scope) => {
      const messageFile = join(scope.root, "msg.txt")
      writeFileSync(messageFile, "feat: parser\n\nGenerated by Claude")
      await plugin.params(SESSION, GPT_5)

      const message = await blocked(plugin.bash(SESSION, `git commit -F ${messageFile}`))

      expect(message).toBe(COMMIT_TRAILER_MESSAGE)
    })
  })

  test.each([
    ["a human co-author", 'git commit -m "fix: backoff\n\nCo-authored-by: Jane Reviewer <jane@example.com>"'],
    ["a non-AI generated-by footer", 'git commit -m "docs: schema\n\nGenerated by the build system"'],
    ["a clean message", 'git commit -m "fix: retry backoff sleeps exponentially"'],
  ])("a git commit with %s passes", async (_label, command) => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      await plugin.bash(SESSION, command)

      expect(plugin.logs).toEqual([])
    })
  })

  test("a posting command with slop is blocked, listing the phrases in pattern order", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      const message = await blocked(plugin.bash(SESSION, 'gh pr comment 42 --body "Great job on this, robust work"'))

      expect(message).toBe(slopMessage("robust, Great job"))
    })
  })

  test("a posting command without the line is blocked with the GPT line", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      const message = await blocked(plugin.bash(SESSION, 'gh issue comment 7 --body "Fixed the timeout."'))

      expect(message).toBe(missingMessage("GPT"))
    })
  })

  test("a posting command with the GPT line passes and is logged", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      await plugin.bash(SESSION, `gh issue comment 7 --body "Fixed the timeout. ${line("GPT")}"`)

      expect(plugin.logs).toEqual([BASH_ALLOWED_LOG])
    })
  })

  test("a bash command that neither commits nor posts is not checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      await plugin.bash(SESSION, "ls -la")

      expect(plugin.logs).toEqual([])
    })
  })

  test.each([
    ["Landed this commit and moved on.", "this commit"],
    ["This PR includes several changes in this PR.", "in this PR"],
    ["A comprehensive rewrite of the module.", "comprehensive"],
    ["The robust solution handles all edge cases.", "robust"],
    ["A seamless upgrade path.", "seamless"],
    ["Great job on the refactor.", "Great job"],
    ["Thanks for this contribution.", "Thanks for this"],
    ["I think maybe we should retry.", "I think maybe"],
    ["You might consider extracting a helper.", "You might consider"],
    ["This is a COMPREHENSIVE change.", "COMPREHENSIVE"],
  ])("an MCP post saying %s is blocked as slop", async (text, phrase) => {
    await withPlugin(async (plugin) => {
      await plugin.params(SESSION, GPT_5)

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post(`${text}\n\n${line("GPT")}`)))

      expect(message).toBe(slopMessage(phrase))
    })
  })
})

describe("opencode-ai-attribution: MCP tools come from the config hook (AC-034)", () => {
  // AC-034: "after the config hook sees mcp = { "github-mcp": {...}, "slack": {...} }, github-mcp_create_issue with a
  //   body and no line throws; slack_post_message passes; mcp__github__create_issue is also checked; write with a
  //   content field is not checked."
  test("github-mcp_create_issue with a body and no line is blocked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config(MCP_SERVERS)

      const message = await blocked(plugin.tool(SESSION, GITHUB_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("github-mcp_create_issue with the line passes and is logged", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config(MCP_SERVERS)

      await plugin.tool(SESSION, GITHUB_TOOL, post(`Fixes the timeout.\n\n${line("AI")}`))

      expect(plugin.logs).toEqual([mcpAllowedLog(GITHUB_TOOL)])
    })
  })

  test("slack_post_message passes without the line", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config(MCP_SERVERS)

      await plugin.tool(SESSION, SLACK_TOOL, { channel: "C1", text: "Deployed the fix." })

      expect(plugin.logs).toEqual([])
    })
  })

  test("mcp__github__create_issue is also checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config(MCP_SERVERS)

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("mcp__slack__post_message passes without the line", async () => {
    await withPlugin(async (plugin) => {
      await plugin.tool(SESSION, "mcp__slack__post_message", { channel: "C1", text: "Deployed the fix." })

      expect(plugin.logs).toEqual([])
    })
  })

  test("write with a content field is not checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config(MCP_SERVERS)

      await plugin.tool(SESSION, "write", { filePath: "/tmp/notes.md", content: "A comprehensive note, no line." })

      expect(plugin.logs).toEqual([])
    })
  })

  test("before the config hook runs, a configured-name tool is not an MCP tool", async () => {
    await withPlugin(async (plugin) => {
      await plugin.tool(SESSION, GITHUB_TOOL, post("Fixes the timeout."))

      expect(plugin.logs).toEqual([])
    })
  })

  test("a config without an mcp key leaves mcp__ tools checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config()

      const message = await blocked(plugin.tool(SESSION, MCP_TOOL, post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("server names are sanitized with opencode's rule before matching", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config({ "corp.jira tools": { type: "remote", url: "https://example.invalid/jira" } })

      const message = await blocked(plugin.tool(SESSION, "corp_jira_tools_create_issue", post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("a server whose name only starts with slack is still checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config({ ...MCP_SERVERS, "slack-archive": { type: "local", command: ["archive-mcp"] } })

      const message = await blocked(plugin.tool(SESSION, "slack-archive_export", post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("the longest configured server prefix decides the server, so slack.archive is still checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config({ ...MCP_SERVERS, "slack.archive": { type: "local", command: ["archive-mcp"] } })

      const message = await blocked(plugin.tool(SESSION, "slack_archive_export", post("Fixes the timeout.")))

      expect(message).toBe(missingMessage("AI"))
    })
  })

  test("an MCP tool call without a body field is not checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config(MCP_SERVERS)

      await plugin.tool(SESSION, "github-mcp_get_issue", { owner: "o", repo: "r", issue_number: 1 })

      expect(plugin.logs).toEqual([])
    })
  })

  test("the first non-empty body field in order is the one checked", async () => {
    await withPlugin(async (plugin) => {
      await plugin.config(MCP_SERVERS)

      await plugin.tool(SESSION, GITHUB_TOOL, { body: "   ", content: line("AI"), text: "No line here." })

      expect(plugin.logs).toEqual([mcpAllowedLog(GITHUB_TOOL)])
    })
  })
})

// Imports the port given as argv[2] and runs one tool call in a session chat.params never saw (family AI): tool argv[4]
// with { body: argv[3] }, or, for "bash", with { command: argv[3] }. Prints {allowed, message} as JSON.
const CHILD_PROBE = [
  "const [port, text, tool] = process.argv.slice(2)",
  "const client = { app: { log: async () => ({ data: true }) } }",
  `const hooks = await (await import(port)).${EXPORT}({ client, directory: process.cwd(), worktree: process.cwd() })`,
  "try {",
  '  const args = tool === "bash" ? { command: text } : { body: text }',
  '  await hooks["tool.execute.before"]({ tool, sessionID: "s", callID: "c" }, { args })',
  '  console.log(JSON.stringify({ allowed: true, message: "" }))',
  "} catch (error) {",
  "  console.log(JSON.stringify({ allowed: false, message: (error as Error).message }))",
  "}",
  "",
].join("\n")

describe("opencode-ai-attribution: name files, in a child bun whose HOME is the scope's", () => {
  const PASSES: ChildResult = { allowed: true, message: "" }
  const NOT_CONFIGURED: ChildResult = { allowed: false, message: SETUP_MESSAGE }

  // A child built from scratch: only PATH is inherited, so neither the real HOME nor the shell's XDG_CONFIG_HOME
  // reaches the port. OVERRIDES maps a variable to undefined to leave it unset.
  function runChild(scope: Scope, body: string, overrides: EnvVars = {}, tool = MCP_TOOL): ChildResult {
    const installed = copyPort(scope, PORT)
    const probe = join(scope.root, "probe.ts")
    writeFileSync(probe, CHILD_PROBE)
    const vars: EnvVars = {
      PATH: process.env.PATH ?? "",
      HOME: scope.home,
      XDG_CONFIG_HOME: scope.configHome,
      XDG_CACHE_HOME: join(scope.root, "cache"),
      XDG_DATA_HOME: join(scope.root, "data"),
      BUN_INSTALL_CACHE_DIR: join(scope.root, "cache", "bun"),
      TMPDIR: scope.root,
      ...overrides,
    }
    const env: Record<string, string> = {}
    for (const [key, value] of Object.entries(vars)) if (value !== undefined) env[key] = value
    const result = spawnSync(process.execPath, [probe, installed, body, tool], {
      cwd: scope.projectDir, env, encoding: "utf8", timeout: 30_000,
    })
    expect({ status: result.status, stderr: result.stderr }).toEqual({ status: 0, stderr: "" })
    return JSON.parse(result.stdout.trim()) as ChildResult
  }

  test("a primary name file that is a directory blocks with the setup message", () => {
    const scope = newScope()
    mkdirSync(primaryNameFile(scope.configHome), { recursive: true })

    expect(runChild(scope, `Fixes the timeout.\n\n${line("AI")}`)).toEqual(NOT_CONFIGURED)
  })

  test("with no name file anywhere, the post is blocked with the setup message and nothing is written", () => {
    const scope = newScope()

    const result = runChild(scope, `Fixes the timeout.\n\n${line("AI")}`)

    expect(result).toEqual(NOT_CONFIGURED)
    expect(readdirSync(scope.home, { recursive: true })).toEqual([])
    expect(existsSync(join(scope.configHome, "llm-agent-workflow"))).toBe(false)
  })

  test("a posting command with no name file anywhere is blocked with the setup message", () => {
    const scope = newScope()

    const result = runChild(scope, `gh pr comment 42 --body "Fixed the timeout. ${line("AI")}"`, {}, "bash")

    expect(result).toEqual(NOT_CONFIGURED)
  })

  test("a name only in the legacy opencode file is read, and no file is written", () => {
    const scope = newScope()
    const legacy = writeName(legacyOpencodeNameFile(scope.home), NAME)

    const result = runChild(scope, `Fixes the timeout.\n\n${line("GPT")}`)

    expect(result).toEqual(PASSES)
    expect(readFileSync(legacy, "utf8")).toBe(NAME)
    expect(existsSync(primaryNameFile(scope.configHome))).toBe(false)
    expect(existsSync(legacyClaudeCodeNameFile(scope.home))).toBe(false)
  })

  test("a name only in the legacy Claude Code file is read", () => {
    const scope = newScope()
    writeName(legacyClaudeCodeNameFile(scope.home), NAME)

    expect(runChild(scope, `Fixes the timeout.\n\n${line("GPT")}`)).toEqual(PASSES)
  })

  test("the legacy opencode file is read before the legacy Claude Code file", () => {
    const scope = newScope()
    writeName(legacyOpencodeNameFile(scope.home), NAME)
    writeName(legacyClaudeCodeNameFile(scope.home), OTHER_NAME)

    const result = runChild(scope, `Fixes the timeout.\n\n${line("AI", OTHER_NAME)}`)

    expect(result).toEqual({ allowed: false, message: missingMessage("AI", NAME) })
  })

  test("the primary file wins over both legacy files", () => {
    const scope = newScope()
    writeName(primaryNameFile(scope.configHome), NAME)
    writeName(legacyOpencodeNameFile(scope.home), OTHER_NAME)
    writeName(legacyClaudeCodeNameFile(scope.home), OTHER_NAME)

    const result = runChild(scope, `Fixes the timeout.\n\n${line("AI", OTHER_NAME)}`)

    expect(result).toEqual({ allowed: false, message: missingMessage("AI", NAME) })
  })

  test("without XDG_CONFIG_HOME, the primary file is read from HOME/.config", () => {
    const scope = newScope()
    writeName(primaryNameFile(join(scope.home, ".config")), NAME)

    const result = runChild(scope, `Fixes the timeout.\n\n${line("AI")}`, { XDG_CONFIG_HOME: undefined })

    expect(result).toEqual(PASSES)
  })

  test("a primary file under HOME/.config is not read when XDG_CONFIG_HOME points elsewhere", () => {
    const scope = newScope()
    writeName(primaryNameFile(join(scope.home, ".config")), NAME)

    expect(runChild(scope, `Fixes the timeout.\n\n${line("AI")}`)).toEqual(NOT_CONFIGURED)
  })

  test.skipIf(IS_ROOT)("an unreadable primary file (mode 000) blocks with the setup message", () => {
    const scope = newScope()
    const primary = writeName(primaryNameFile(scope.configHome), NAME)
    chmodSync(primary, 0o000)

    const result = runChild(scope, `Fixes the timeout.\n\n${line("AI")}`)
    chmodSync(primary, 0o600)

    expect(result).toEqual(NOT_CONFIGURED)
  })

  test("an undecodable primary file blocks with the setup message", () => {
    const scope = newScope()
    writeName(primaryNameFile(scope.configHome), new Uint8Array([0xff, 0xfe, 0xfa]))

    expect(runChild(scope, `Fixes the timeout.\n\n${line("AI")}`)).toEqual(NOT_CONFIGURED)
  })

  test("a primary that is a directory falls through to the legacy opencode file", () => {
    const scope = newScope()
    mkdirSync(primaryNameFile(scope.configHome), { recursive: true })
    writeName(legacyOpencodeNameFile(scope.home), NAME)

    expect(runChild(scope, `Fixes the timeout.\n\n${line("AI")}`)).toEqual(PASSES)
  })

  test("an empty primary file falls through to the legacy Claude Code file", () => {
    const scope = newScope()
    writeName(primaryNameFile(scope.configHome), "  \n")
    writeName(legacyClaudeCodeNameFile(scope.home), NAME)

    expect(runChild(scope, `Fixes the timeout.\n\n${line("AI")}`)).toEqual(PASSES)
  })
})
