#!/usr/bin/env python3
"""Unit + end-to-end tests for the claude-attribution PreToolUse hook.

Run with either:

  python3 -m unittest discover -s plugin-attribution/tests
  python3 -m pytest plugin-attribution/tests

The end-to-end tests invoke the real hook binary in a subprocess with a
temporary HOME so the reviewer-name file never touches the real one.
"""

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HOOK_DIR = Path(__file__).resolve().parents[1] / "hooks"
HOOK = HOOK_DIR / "attribution_hook.py"
NAME = "Jane Reviewer"

sys.path.insert(0, str(HOOK_DIR))
import attribution_hook as hook  # noqa: E402


def run_hook(tool_name, tool_input, home):
    """Run the hook binary with a JSON payload; return (exit_code, stderr)."""
    payload = json.dumps({"tool_name": tool_name, "tool_input": tool_input})
    env = dict(os.environ, HOME=str(home))
    proc = subprocess.run(
        [sys.executable, str(HOOK)],
        input=payload,
        capture_output=True,
        text=True,
        env=env,
    )
    return proc.returncode, proc.stderr


def make_home(tmpdir):
    """Create a temp HOME with the reviewer name file; return the dir."""
    home = Path(tmpdir) / "home"
    (home / ".claude").mkdir(parents=True)
    (home / ".claude" / "claude-attribution-name.txt").write_text(NAME)
    return home


class HasAttributionTests(unittest.TestCase):
    def test_attribution_pass(self):
        body = "Fixed the flaky test.\n\n🤖 Written by Claude, reviewed by Jane Reviewer"
        self.assertTrue(hook.has_attribution(body, NAME))

    def test_attribution_pass_without_emoji(self):
        body = "Fixed the flaky test.\n\nWritten by Claude, reviewed by Jane Reviewer"
        self.assertTrue(hook.has_attribution(body, NAME))

    def test_attribution_fail_missing(self):
        self.assertFalse(hook.has_attribution("Just a plain comment.", NAME))

    def test_attribution_fail_wrong_reviewer(self):
        body = "🤖 Written by Claude, reviewed by Someone Else"
        self.assertFalse(hook.has_attribution(body, NAME))


class NativeAttributionTests(unittest.TestCase):
    def test_slack_mcp_is_exempt(self):
        self.assertTrue(hook.has_native_attribution("mcp__slack__postMessage"))

    def test_other_mcp_is_not_exempt(self):
        self.assertFalse(hook.has_native_attribution("mcp__github__create_issue"))


class SlopPhraseTests(unittest.TestCase):
    def test_each_banned_phrase_is_detected(self):
        cases = [
            "Landed this commit and moved on.",
            "This PR includes several changes in this PR.",
            "A comprehensive rewrite of the module.",
            "The robust solution handles all edge cases.",
            "Great job on the refactor.",
            "Thanks for this contribution.",
            "I think maybe we should retry.",
            "You might consider extracting a helper.",
        ]
        for text in cases:
            with self.subTest(text=text):
                self.assertTrue(hook.find_slop_phrases(text), text)

    def test_slop_detection_is_case_insensitive(self):
        self.assertTrue(hook.find_slop_phrases("This is a COMPREHENSIVE change."))

    def test_clean_text_has_no_slop(self):
        text = (
            "The retry loop now backs off exponentially. "
            "Added a regression test for the timeout path."
        )
        self.assertEqual(hook.find_slop_phrases(text), [])


class CommitTrailerTests(unittest.TestCase):
    def test_co_authored_by_ai_is_detected(self):
        messages = ["fix: retry backoff\n\nCo-authored-by: Claude 3.7 Sonnet <noreply@anthropic.com>"]
        self.assertTrue(hook.has_ai_trailer(messages))

    def test_generated_by_ai_is_detected(self):
        self.assertTrue(hook.has_ai_trailer(["feat: parser\n\nGenerated by Claude"]))

    def test_assisted_by_ai_is_detected(self):
        self.assertTrue(hook.has_ai_trailer(["refactor: moved types\n\nAssisted by Copilot"]))

    def test_human_co_author_is_allowed(self):
        messages = ["fix: backoff\n\nCo-authored-by: Jane Reviewer <jane@example.com>"]
        self.assertFalse(hook.has_ai_trailer(messages))

    def test_non_ai_generated_by_is_allowed(self):
        self.assertFalse(hook.has_ai_trailer(["docs: schema\n\nGenerated by the build system"]))

    def test_clean_message_is_allowed(self):
        self.assertFalse(hook.has_ai_trailer(["fix: retry backoff sleeps exponentially"]))

    def test_extract_messages_from_dash_m(self):
        self.assertEqual(
            hook.find_commit_messages('git commit -m "fix: backoff"'),
            ["fix: backoff"],
        )

    def test_extract_messages_from_combined_short_flags(self):
        self.assertEqual(
            hook.find_commit_messages('git commit -am "fix: backoff"'),
            ["fix: backoff"],
        )

    def test_extract_messages_from_multiple_dash_m(self):
        messages = hook.find_commit_messages(
            'git commit -m "fix: backoff" -m "Added regression test"'
        )
        self.assertEqual(messages, ["fix: backoff", "Added regression test"])

    def test_extract_message_files_from_dash_F(self):
        self.assertEqual(
            hook.find_commit_message_files("git commit -F /tmp/msg.txt"),
            ["/tmp/msg.txt"],
        )


class EndToEndTests(unittest.TestCase):
    """Real hook binary, subprocess, temp HOME."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.home = make_home(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    # --- Attribution pass/fail ---

    def test_mcp_post_with_attribution_allowed(self):
        code, _ = run_hook(
            "mcp__github__create_issue",
            {"title": "Fix flaky test", "body": f"Fixes timeout.\n\n🤖 Written by Claude, reviewed by {NAME}"},
            self.home,
        )
        self.assertEqual(code, 0)

    def test_mcp_post_without_attribution_blocked(self):
        code, stderr = run_hook(
            "mcp__github__create_issue",
            {"title": "Fix flaky test", "body": "Fixes timeout."},
            self.home,
        )
        self.assertEqual(code, 2)
        self.assertIn("Attribution line missing", stderr)

    # --- Native-attribution bypass ---

    def test_slack_mcp_bypasses_checks(self):
        code, _ = run_hook(
            "mcp__slack__postMessage",
            {"channel": "#dev", "text": "Comprehensive update, great job everyone."},
            self.home,
        )
        self.assertEqual(code, 0)

    # --- Slop phrase block ---

    def test_mcp_post_with_slop_blocked(self):
        code, stderr = run_hook(
            "mcp__github__create_issue",
            {"title": "Fix flaky test", "body": "This is a comprehensive fix."},
            self.home,
        )
        self.assertEqual(code, 2)
        self.assertIn("AI-slop filler detected", stderr)

    def test_bash_post_with_slop_blocked(self):
        code, _ = run_hook(
            "Bash",
            {"command": f'gh pr comment 42 --body "Great job on this, robust work"'},
            self.home,
        )
        self.assertEqual(code, 2)

    # --- Commit trailer block ---

    def test_commit_dash_m_with_ai_trailer_blocked(self):
        code, stderr = run_hook(
            "Bash",
            {"command": 'git commit -m "fix: backoff\n\nCo-authored-by: Claude <noreply@anthropic.com>"'},
            self.home,
        )
        self.assertEqual(code, 2)
        self.assertIn("AI-generated trailer detected", stderr)

    def test_commit_dash_m_clean_allowed(self):
        code, _ = run_hook(
            "Bash",
            {"command": 'git commit -m "fix: retry backoff sleeps exponentially"'},
            self.home,
        )
        self.assertEqual(code, 0)

    def test_commit_dash_F_with_ai_trailer_blocked(self):
        msg_file = Path(self._tmp.name) / "msg.txt"
        msg_file.write_text("feat: parser\n\nGenerated by Claude")
        code, _ = run_hook(
            "Bash",
            {"command": f"git commit -F {msg_file}"},
            self.home,
        )
        self.assertEqual(code, 2)

    # --- Non-posting Bash untouched ---

    def test_unrelated_bash_command_allowed(self):
        code, _ = run_hook("Bash", {"command": "ls -la"}, self.home)
        self.assertEqual(code, 0)


if __name__ == "__main__":
    unittest.main()