import { readFileSync } from "node:fs"
import { homedir } from "node:os"
import { join } from "node:path"
import type { Plugin } from "@opencode-ai/plugin"

/**
 * opencode-claude-attribution plugin.
 *
 * Anti-AI-slop + attribution governance for external posts:
 *   - blocks posts that lack the "🤖 Written by Claude, reviewed by <user>"
 *     attribution line (dynamic, ANY MCP server)
 *   - blocks clear AI-slop filler phrases in post bodies / posting commands
 *   - blocks AI-generated trailers in `git commit` messages
 *
 * OpenCode port of the Claude Code PreToolUse hook
 * (plugin-attribution/hooks/attribution_hook.py):
 *   - `tool.execute.before` for `bash`  -> was `Bash` matcher branch
 *   - `tool.execute.before` for `mcp__*` -> was `mcp__.*` matcher branch
 *   - `throw new Error(...)`             -> was `sys.exit(2)` block
 */

const NAME_FILE = join(homedir(), ".config", "opencode", "claude-attribution-name.txt")

// MCP tool name patterns that provide native AI attribution,
// so the text attribution line is not required.
// Slack adds "Sent using @Claude" natively when posting via its AI integration.
const NATIVE_ATTRIBUTION_TOOL_PATTERNS = [
  "^mcp__slack__",
]

// Fields that typically contain postable text body.
// Checked in order — first non-empty match wins.
const BODY_FIELDS = [
  "body",
  "content",
  "message",
  "comment",
  "commentBody",
  "description",
  "text",
]

// Bash patterns that post to external platforms
const POSTING_BASH_PATTERNS = [
  "\\bgh\\s+pr\\s+(create|comment|review|edit)\\b",
  "\\bgh\\s+issue\\s+(create|comment|edit)\\b",
  "\\bgh\\s+api\\b.*(-f\\s+body=|--field\\s+body=|-F\\s+body=|--raw-field\\s+body=)",
  "\\bcurl\\s+.*-X\\s*(POST|PUT|PATCH)",
  "\\bcurl\\s+.*--data",
  "\\bjira\\s+issue\\s+(create|comment)",
]

// Filler phrases that read as AI slop. Blocked in any external post body or
// posting command. Case-insensitive.
const SLOP_PHRASES = [
  "\\bthis\\s+commit\\b",
  "\\bin\\s+this\\s+PR\\b",
  "\\bcomprehensive\\b",
  "\\brobust\\b",
  "\\bseamless\\b",
  "\\bgreat\\s+job\\b",
  "\\bthanks\\s+for\\s+this\\b",
  "\\bI\\s+think\\s+maybe\\b",
  "\\byou\\s+might\\s+consider\\b",
]

// `git commit` invocations that carry a message inline (-m/--message,
// including combined short flags like -am) or in a file (-F/--file).
const COMMIT_COMMAND_PATTERN =
  "\\bgit\\s+commit\\b.*?\\s(?:--message\\b|--file\\b|-{1,2}[\\w-]*m\\b|-{1,2}[\\w-]*F\\b)"

// AI-model terms that mark a co-author/trailer as machine-generated.
const AI_TERMS = [
  "claude",
  "anthropic",
  "copilot",
  "chatgpt",
  "gpt",
  "openai",
  "gemini",
  "bard",
  "deepseek",
  "mistral",
  "llama",
  "llm",
  "ai",
]

// AI-trailer patterns blocked in commit messages (case-insensitive):
//   - "Co-authored-by: <AI name>" lines
//   - "generated by/with <AI>", "assisted by <AI>" footer lines
const COMMIT_AI_TRAILER_PATTERNS = [
  "co-authored-by:\\s*[^\\n]*\\b(?:" + AI_TERMS.join("|") + ")\\b",
  "(?:generated|created|written|assisted)\\s+(?:by|with)\\s+[^\\n]*\\b(?:"
    + AI_TERMS.join("|")
    + ")\\b",
]

const SETUP_MESSAGE = `[opencode-claude-attribution] BLOCKED: Reviewer name not configured.

Before posting to external platforms, set up your attribution name.
Ask the user for their name and save it:

  echo "Their Name" > ~/.config/opencode/claude-attribution-name.txt

Then show the complete post content to the user for approval before retrying.`

const MISSING_MESSAGE = (name: string) => `[opencode-claude-attribution] BLOCKED: Attribution line missing from post body.

All external posts must include this attribution line:

  🤖 Written by Claude, reviewed by ${name}

IMPORTANT: Before retrying, you MUST:
1. Add the attribution line to the post body
2. Show the COMPLETE post content to the user
3. Ask the user to approve before posting
4. Only retry after user confirms`

const COMMIT_TRAILER_MESSAGE = `[opencode-claude-attribution] BLOCKED: AI-generated trailer detected in commit message.

Remove AI attribution trailers from the commit message:
  - "Co-authored-by:" lines naming an AI model or assistant
  - "generated by/with <AI>" or "assisted by <AI>" lines

Keep the commit message concise, factual, and free of AI attribution. Then
retry the commit.`

const SLOP_MESSAGE = (phrases: string) => `[opencode-claude-attribution] BLOCKED: AI-slop filler detected in post content.

Remove these phrases and rewrite with concrete, specific language:
  ${phrases}

Prefer plain, factual wording that states what changed and why. For review
comments, structure feedback as: location -> problem -> proposed fix.

IMPORTANT: Rewrite the content, show the COMPLETE updated post to the user,
and get approval before retrying.`

function getReviewerName(): string | null {
  try {
    const name = readFileSync(NAME_FILE, "utf8").trim()
    return name || null
  } catch {
    return null
  }
}

function findBodyField(args: Record<string, unknown>): [string, string] | null {
  for (const field of BODY_FIELDS) {
    const value = args[field]
    if (typeof value === "string" && value.trim()) {
      return [field, value]
    }
  }
  return null
}

function hasNativeAttribution(toolName: string): boolean {
  /** Return true if the tool provides native AI attribution (e.g. Slack's 'Sent using @Claude'). */
  return NATIVE_ATTRIBUTION_TOOL_PATTERNS.some((pattern) =>
    new RegExp(pattern).test(toolName),
  )
}

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function hasAttribution(text: string, name: string): boolean {
  const pattern = new RegExp(
    "(🤖\\s*)?written\\s+by\\s+claude.*reviewed\\s+by\\s+" + escapeRegExp(name),
    "i",
  )
  return pattern.test(text)
}

function findSlopPhrases(text: string): string[] {
  /** Return the AI-slop filler phrases found in text, in match order. */
  const found: string[] = []
  for (const pattern of SLOP_PHRASES) {
    const match = text.match(new RegExp(pattern, "i"))
    if (match) found.push(match[0].trim())
  }
  return found
}

function findCommitMessages(command: string): string[] {
  /** Extract quoted messages from `git commit -m/--message` (incl. `-am`). */
  const messages: string[] = []
  const pattern = new RegExp(
    "(?:--message\\b|(?:^|[\\s;|&])-{1,2}[\\w-]*m\\b)\\s*([\"'])(.*?)\\1",
    "is",
  )
  for (const match of command.matchAll(pattern)) {
    messages.push(match[2])
  }
  return messages
}

function findCommitMessageFiles(command: string): string[] {
  /** Extract file paths given to `git commit -F/--file` flags. */
  const files: string[] = []
  const pattern = new RegExp(
    "(?:--file\\b|(?:^|[\\s;|&])-{1,2}[\\w-]*F\\b)\\s*(\\S+)",
    "i",
  )
  for (const match of command.matchAll(pattern)) {
    files.push(match[1].replace(/^["']|["']$/g, ""))
  }
  return files
}

function commitMessages(command: string): string[] {
  /** Collect the effective commit message text from a `git commit` command. */
  const messages = findCommitMessages(command)
  for (const file of findCommitMessageFiles(command)) {
    try {
      messages.push(readFileSync(file, "utf8"))
    } catch {
      // file not readable yet; git itself will fail the commit
    }
  }
  return messages
}

function hasAiTrailer(messages: string[]): boolean {
  /** Return true if any commit message carries an AI-generated trailer. */
  for (const message of messages) {
    for (const pattern of COMMIT_AI_TRAILER_PATTERNS) {
      if (new RegExp(pattern, "i").test(message)) return true
    }
  }
  return false
}

// Per-session Claude-model flag. Updated by chat.params on each model call;
// checked by tool.execute.before to skip enforcement for non-Claude LLMs
// (the attribution line literally claims "Written by Claude").
const sessionIsClaude = new Map<string, boolean>()

function isClaudeSession(sessionID: string): boolean {
  return sessionIsClaude.get(sessionID) === true
}

export const ClaudeAttributionPlugin: Plugin = async ({ client }) => {
  return {
    "chat.params": async (input) => {
      // Anthropic provider + claude model family = Claude LLM
      sessionIsClaude.set(
        input.sessionID,
        input.model.providerID === "anthropic" &&
          input.model.modelID.toLowerCase().includes("claude"),
      )
    },

    "tool.execute.before": async (input, output) => {
      // Plugin is Claude-only — skip enforcement for other LLMs.
      if (!isClaudeSession(input.sessionID)) return

      const args = (output.args ?? {}) as Record<string, unknown>

      // --- Bash: commit-quality check, then posting-command checks ---
      if (input.tool === "bash") {
        const command = typeof args.command === "string" ? args.command : ""

        // `git commit` with an inline or file-supplied message -> AI-trailer check
        if (new RegExp(COMMIT_COMMAND_PATTERN, "i").test(command)) {
          if (hasAiTrailer(commitMessages(command))) {
            throw new Error(COMMIT_TRAILER_MESSAGE)
          }
          return
        }

        const isPosting = POSTING_BASH_PATTERNS.some((pattern) =>
          new RegExp(pattern, "i").test(command),
        )
        if (!isPosting) return

        const slop = findSlopPhrases(command)
        if (slop.length > 0) {
          throw new Error(SLOP_MESSAGE(slop.join(", ")))
        }

        const name = getReviewerName()
        if (!name) {
          throw new Error(SETUP_MESSAGE)
        }
        if (!hasAttribution(command, name)) {
          throw new Error(MISSING_MESSAGE(name))
        }

        await client.app.log({
          body: {
            service: "opencode-claude-attribution",
            level: "info",
            message: `Bash posting command allowed with attribution`,
          },
        })
        return
      }

      // --- MCP tools: dynamic body field detection ---
      if (!input.tool.startsWith("mcp__")) return

      // Some MCP servers (e.g. Slack) provide native AI attribution.
      // Skip the text attribution check for those tools.
      if (hasNativeAttribution(input.tool)) return

      const result = findBodyField(args)
      if (result === null) return

      const bodyText = result[1]

      const slop = findSlopPhrases(bodyText)
      if (slop.length > 0) {
        throw new Error(SLOP_MESSAGE(slop.join(", ")))
      }

      const name = getReviewerName()
      if (!name) {
        throw new Error(SETUP_MESSAGE)
      }

      if (!hasAttribution(bodyText, name)) {
        throw new Error(MISSING_MESSAGE(name))
      }

      await client.app.log({
        body: {
          service: "opencode-claude-attribution",
          level: "info",
          message: `MCP post allowed with attribution (${input.tool})`,
        },
      })
    },
  }
}