#!/usr/bin/env python3
"""
claude-attribution PreToolUse hook.

Anti-AI-slop + attribution governance for external posts:

- Blocks external posts that lack the "🤖 Written by Claude, reviewed by <user>"
  attribution line. Works dynamically with ANY MCP server.
- Blocks clear AI-slop filler phrases in post bodies / posting commands.
- Blocks AI-generated trailers in `git commit` messages
  ("Co-authored-by:" lines naming AI models, "generated by/with <AI>",
  "assisted by <AI>").

Exit codes:
  0 - Allow the tool call to proceed
  2 - Block the tool call; stderr message is fed back to Claude as context
"""

import json
import re
import sys
from pathlib import Path

NAME_FILE = Path.home() / ".claude" / "claude-attribution-name.txt"

# MCP tool name patterns that provide native AI attribution,
# so the text attribution line is not required.
# Slack adds "Sent using @Claude" natively when posting via its AI integration.
NATIVE_ATTRIBUTION_TOOL_PATTERNS = [
    r"^mcp__slack__",
]

# Fields that typically contain postable text body.
# Checked in order — first non-empty match wins.
BODY_FIELDS = [
    "body",
    "content",
    "message",
    "comment",
    "commentBody",
    "description",
    "text",
]

# Bash patterns that post to external platforms
POSTING_BASH_PATTERNS = [
    r"\bgh\s+pr\s+(create|comment|review|edit)\b",
    r"\bgh\s+issue\s+(create|comment|edit)\b",
    r"\bgh\s+api\b.*(-f\s+body=|--field\s+body=|-F\s+body=|--raw-field\s+body=)",
    r"\bcurl\s+.*-X\s*(POST|PUT|PATCH)",
    r"\bcurl\s+.*--data",
    r"\bjira\s+issue\s+(create|comment)",
]

# Filler phrases that read as AI slop. Blocked in any external post body or
# posting command. Case-insensitive.
SLOP_PHRASES = [
    r"\bthis\s+commit\b",
    r"\bin\s+this\s+PR\b",
    r"\bcomprehensive\b",
    r"\brobust\b",
    r"\bseamless\b",
    r"\bgreat\s+job\b",
    r"\bthanks\s+for\s+this\b",
    r"\bI\s+think\s+maybe\b",
    r"\byou\s+might\s+consider\b",
]

# `git commit` invocations that carry a message inline (-m/--message,
# including combined short flags like -am) or in a file (-F/--file).
COMMIT_COMMAND_PATTERN = re.compile(
    r"\bgit\s+commit\b.*?\s(?:--message\b|--file\b|-{1,2}[\w-]*m\b|-{1,2}[\w-]*F\b)",
    re.IGNORECASE,
)

# AI-model terms that mark a co-author/trailer as machine-generated.
AI_TERMS = [
    "claude",
    "anthropic",
    "copilot",
    "chatgpt",
    "gpt",
    "openai",
    "gemini",
    "bard",
    "deepseek",
    "mistral",
    "llama",
    "llm",
    "ai",
]

# AI-trailer patterns blocked in commit messages:
#   - "Co-authored-by: <AI name>" lines (the AI attribution trailer)
#   - "generated by/with <AI>", "assisted by <AI>" footer lines
COMMIT_AI_TRAILER_PATTERNS = [
    r"co-authored-by:\s*[^\n]*\b(?:" + "|".join(AI_TERMS) + r")\b",
    r"(?:generated|created|written|assisted)\s+(?:by|with)\s+[^\n]*\b(?:"
    + "|".join(AI_TERMS)
    + r")\b",
]

SETUP_MESSAGE = """\
[claude-attribution] BLOCKED: Reviewer name not configured.

Before posting to external platforms, set up your attribution name.
Ask the user for their name and save it:

  echo "Their Name" > ~/.claude/claude-attribution-name.txt

Then show the complete post content to the user for approval before retrying."""

MISSING_MESSAGE = """\
[claude-attribution] BLOCKED: Attribution line missing from post body.

All external posts must include this attribution line:

  🤖 Written by Claude, reviewed by {name}

IMPORTANT: Before retrying, you MUST:
1. Add the attribution line to the post body
2. Show the COMPLETE post content to the user
3. Ask the user to approve before posting
4. Only retry after user confirms"""

SLOP_MESSAGE = """\
[claude-attribution] BLOCKED: AI-slop filler detected in post content.

Remove these phrases and rewrite with concrete, specific language:
  {phrases}

Prefer plain, factual wording that states what changed and why. For review
comments, structure feedback as: location -> problem -> proposed fix.

IMPORTANT: Rewrite the content, show the COMPLETE updated post to the user,
and get approval before retrying."""

COMMIT_TRAILER_MESSAGE = """\
[claude-attribution] BLOCKED: AI-generated trailer detected in commit message.

Remove AI attribution trailers from the commit message:
  - "Co-authored-by:" lines naming an AI model or assistant
  - "generated by/with <AI>" or "assisted by <AI>" lines

Keep the commit message concise, factual, and free of AI attribution. Then
retry the commit."""


def get_reviewer_name() -> "str | None":
    try:
        name = NAME_FILE.read_text().strip()
        return name or None
    except FileNotFoundError:
        return None


def find_body_field(tool_input: dict) -> "tuple[str, str] | None":
    for field in BODY_FIELDS:
        value = tool_input.get(field)
        if isinstance(value, str) and value.strip():
            return (field, value)
    return None


def has_native_attribution(tool_name: str) -> bool:
    """Return True if the tool provides native AI attribution (e.g. Slack's 'Sent using @Claude')."""
    return any(
        re.search(pattern, tool_name) for pattern in NATIVE_ATTRIBUTION_TOOL_PATTERNS
    )


def has_attribution(text: str, name: str) -> bool:
    pattern = re.compile(
        r"(\U0001f916\s*)?written\s+by\s+claude.*reviewed\s+by\s+" + re.escape(name),
        re.IGNORECASE,
    )
    return bool(pattern.search(text))


def find_slop_phrases(text: str) -> "list[str]":
    """Return the AI-slop filler phrases found in text, in match order."""
    found = []
    for pattern in SLOP_PHRASES:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            found.append(match.group(0).strip())
    return found


def find_commit_messages(command: str) -> "list[str]":
    """Extract quoted message strings from `git commit -m/--message` flags.

    Covers plain `-m "msg"` and combined short flags such as `-am "msg"`.
    """
    messages = []
    pattern = re.compile(
        r"(?:--message\b|(?:^|[\s;|&])-{1,2}[\w-]*m\b)\s*([\"'])(.*?)\1",
        re.IGNORECASE | re.DOTALL,
    )
    for match in pattern.finditer(command):
        messages.append(match.group(2))
    return messages


def find_commit_message_files(command: str) -> "list[str]":
    """Extract file paths given to `git commit -F/--file` flags."""
    pattern = re.compile(
        r"(?:--file\b|(?:^|[\s;|&])-{1,2}[\w-]*F\b)\s*(\S+)",
        re.IGNORECASE,
    )
    return [match.group(1).strip("\"'") for match in pattern.finditer(command)]


def commit_messages(command: str) -> "list[str]":
    """Collect the effective commit message text from a `git commit` command."""
    messages = find_commit_messages(command)
    for path in find_commit_message_files(command):
        try:
            messages.append(Path(path).read_text())
        except OSError:
            continue  # file not readable yet; git itself will fail the commit
    return messages


def has_ai_trailer(messages: "list[str]") -> bool:
    """Return True if any commit message carries an AI-generated trailer."""
    for message in messages:
        for pattern in COMMIT_AI_TRAILER_PATTERNS:
            if re.search(pattern, message, re.IGNORECASE):
                return True
    return False


def main() -> None:
    try:
        data = json.loads(sys.stdin.read())
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)

    tool_name: str = data.get("tool_name", "")
    tool_input: dict = data.get("tool_input", {})

    # --- Bash: commit-quality check, then posting-command checks ---
    if tool_name == "Bash":
        command: str = tool_input.get("command", "")

        # `git commit` with an inline or file-supplied message -> AI-trailer check
        if COMMIT_COMMAND_PATTERN.search(command):
            if has_ai_trailer(commit_messages(command)):
                print(COMMIT_TRAILER_MESSAGE, file=sys.stderr)
                sys.exit(2)
            sys.exit(0)

        is_posting = any(
            re.search(p, command, re.IGNORECASE) for p in POSTING_BASH_PATTERNS
        )
        if not is_posting:
            sys.exit(0)

        slop = find_slop_phrases(command)
        if slop:
            print(SLOP_MESSAGE.format(phrases=", ".join(slop)), file=sys.stderr)
            sys.exit(2)

        name = get_reviewer_name()
        if not name:
            print(SETUP_MESSAGE, file=sys.stderr)
            sys.exit(2)
        if not has_attribution(command, name):
            print(MISSING_MESSAGE.format(name=name), file=sys.stderr)
            sys.exit(2)
        sys.exit(0)

    # --- MCP tools: dynamic body field detection ---
    if not tool_name.startswith("mcp__"):
        sys.exit(0)

    # Some MCP servers (e.g. Slack) provide native AI attribution.
    # Skip the text attribution check for those tools.
    if has_native_attribution(tool_name):
        sys.exit(0)

    result = find_body_field(tool_input)
    if result is None:
        sys.exit(0)

    _field_name, body_text = result

    slop = find_slop_phrases(body_text)
    if slop:
        print(SLOP_MESSAGE.format(phrases=", ".join(slop)), file=sys.stderr)
        sys.exit(2)

    name = get_reviewer_name()
    if not name:
        print(SETUP_MESSAGE, file=sys.stderr)
        sys.exit(2)

    if not has_attribution(body_text, name):
        print(MISSING_MESSAGE.format(name=name), file=sys.stderr)
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()